### PR TITLE
Add TrueJob

### PR DESCRIPTION
**Pull request by JangoSteve**
Added TrueJob.

### CODE REVIEW

**Comment by scouttyg** [comment]
:+1:

**Comment by scouttyg** [comment]
Hey @sampl, just checking back in again. Hope you can add in TrueJob!

**Comment by sampl** [comment]
Hi @JangoSteve and @scouttyg, thanks for adding--would you mind posting a little about TrueJob traction? https://github.com/sampl/madeina2/blob/master/README.md

**Comment by scouttyg** [comment]
Hey @sampl -- I read over the criteria for the site, and I've met the criteria for all three -- there are well over 1k users on the site, I'm based out of Ann Arbor, I'm open to the public, and I'm a SaaS.  You can also see highly upvoted references [here on Hacker News](https://news.ycombinator.com/item?id=8644172 ), and on [Reddit](https://www.reddit.com/r/startups/comments/2mtu29/show_rstartups_truejob_okcupid_for_jobs/)

Let me know what other details you need, or verification I would need to provide.

**Comment by scouttyg** [comment]
@sampl Just checking back in to see if I can provide more data, but I meet the criteria you posted.

**Comment by scouttyg** [comment]
Since this has merge conflicts and @JangoSteve was the original submitter of this (so it's hard for me to fix those merge conflicts), I added a new pull request in #35 that mirrors these changes, and allows me to fix anything if need be should other conflicts arise.

Let me know if I can provide any more help @sampl!

**Comment by sampl** [comment]
merged in https://github.com/sampl/madeina2/pull/35

**Pull request closed without merging**
